#!/bin/bash
db="$1"
user="$2"
port="$3"

bash docker-entrypoint-initdb.d/1.0.1-Referees.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.2-Countries.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.3-Cities.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.4-Stadiums.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.5-Clubs.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.6-Trainers.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.7-PlayerPosition.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.8-Players.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.9-Games.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.10-Games-Referees.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.11-Goals.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.0.12-Penalties.sh "$db" "$user" "$port"

echo "Filling tables"
bash docker-entrypoint-initdb.d/1.1.0-Referees.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.1-Countries.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.2-Cities.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.3-Stadiums.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.4-Clubs.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.5-train.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.1.6-Players.sh "$db" "$user" "$port"
echo "Players filled"
bash docker-entrypoint-initdb.d/1.1.7-Games.sh "$db" "$user" "$port"
echo "Games filled"
bash docker-entrypoint-initdb.d/1.1.8-Games-Referees.sh "$db" "$user" "$port"
echo "Games_referees filled"
bash docker-entrypoint-initdb.d/1.1.9-Goals.sh "$db" "$user" "$port"
echo "Goals filled"
bash docker-entrypoint-initdb.d/1.1.10-Penalties.sh "$db" "$user" "$port"
echo "Penalties filled"

bash docker-entrypoint-initdb.d/1.2.0-Writer.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.2.1-Reader.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.2.2-analyt.sh "$db" "$user" "$port"
bash docker-entrypoint-initdb.d/1.2.3-GroupRole.sh "$db" "$user" "$port"