version: "3.9"

volumes:
  scripts:

name: "db-hw2"

services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    restart: unless-stopped
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/scripts
      - ./docker-compose.yml:/app/resources/docker-compose.yml
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5000
      - POSTGRES_PASSWORD=kosandron
      - POSTGRES_USER=1234
      - VERSION=1.2.3
      - POSTGRES_USERS=user1,user2,user3
      - BIGTABLESIZE=1000000
      - SMALLTABLESIZE=1000
      - EXPLAIN_CALLS=5
      - BACKUPS_COPIES=2
      - BACKUPS_FREQUENCY=1
